// Why? Because I wanted to.

/**
 * Gets a random integer between the specified minimum and maximum values, inclusive.
 *
 * @param min
 * @param max
 * @returns
 */
function getRandomInt(min: number, max: number) {
  return Math.floor(Math.random() * (max - min + 1) + min)
}

/**
 * Generate a random byte.
 *
 * @returns A random byte
 */
function generateRandomByte() {
  return getRandomInt(0, 255)
}

/**
 * Generate a random byte and convert it to a hexadecimal string.
 *
 * @returns A random byte as a hexadecimal string
 */
function generateRandomHexByte() {
  return generateRandomByte().toString(16).padStart(2, '0')
}

/**
 * Generate a random byte with the two most significant bits set to 10. This is used to set the variant in a UUID, which in our case is the variant specified in RFC 4122.
 *
 * https://datatracker.ietf.org/doc/html/rfc4122#section-4.1.1
 *
 * @returns A random byte with the two most significant bits set to 10
 */
function generateVariantHexByte() {
  // zero out the two most significant bits in the randomly generated byte and then set them to 10
  const byte = (generateRandomByte() & 0b00111111) | 0b10000000
  return byte.toString(16).padStart(2, '0')
}

/**
 * Generate a pseudo-random version 4 UUID based on RFC 4122
 * https://datatracker.ietf.org/doc/html/rfc4122
 *
 * This function is not cryptographically secure, but it is good enough for most use cases and the probability of collision is low.
 * @returns A pseudo-random version 4 UUID
 */
export function generateId(): string {
  // these are just named by convention for time-based UUIDs; this isn't actually a time-based UUID but I'm keeping the names for consistency

  // 8 bytes for the low field of the timestamp
  const low_time =
    generateRandomHexByte() +
    generateRandomHexByte() +
    generateRandomHexByte() +
    generateRandomHexByte()

  // 4 bytes for the middle field of the timestamp
  const mid_time = generateRandomHexByte() + generateRandomHexByte()

  // 4 bytes for the version, starting with 4 to indicate UUID v4
  const version =
    '4' + generateRandomHexByte().substring(1) + generateRandomHexByte()

  // 4 bytes for the variant, with the first two bytes indicating the variant and the last two bytes being random
  const variant = generateVariantHexByte() + generateRandomHexByte()

  // 12 bytes for the node
  const node =
    generateRandomHexByte() +
    generateRandomHexByte() +
    generateRandomHexByte() +
    generateRandomHexByte() +
    generateRandomHexByte() +
    generateRandomHexByte()

  return `${low_time}-${mid_time}-${version}-${variant}-${node}`
}
